package:
  name: mlir
  version: 20.1.1
source:
  git: https://github.com/KULeuven-MICAS/llvm-build
  rev: ${{ version }}
about:
  homepage: https://github.com/KULeuven-MICAS/llvm-build
  summary: "MLIR Builds"
